version: 0.2

phases:
  install:
    commands:
      - echo Install npm packages...
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Building on `date`...
      - npm run prepare
      - aws cloudformation package --template-file config/samTemplate.yml --s3-bucket $CLOUDFORMATION_S3_BUCKET --s3-prefix $CLOUDFORMATION_S3_PATH --output-template-file outputSamTemplate.yml
  post_build:
    commands:
      - echo Nothing to do in the post_build phase...

artifacts:
  type: zip
  files:
    - config/samTemplate.yml
    - outputSamTemplate.yml

cache:
  paths:
    - node_modules
