version: 0.2

phases:
  install:
    commands:
      - echo Install npm packages...
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Building on `date`...
      - npm run prepare
      - ws cloudformation package --template-file samTemplate.yml --s3-bucket $CLOUDFORMATION_S3_BUCKET
                                           --output-template-file outputSamTemplate.yml
  post_build:
    commands:
      - echo Nothing to do in the post_build phase...

artifacts:
  type: zip
  files:
    - dist/**/*
    - node_modules/**/*
    - samTemplate.yml
    - outputSamTemplate.yml

cache:
  paths:
    - node_modules
