AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World
Resources:
  HelloWorldTS:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/events/helloWorld.handler
      Runtime: nodejs8.10
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /
            Method: GET
        PostResource:
          Type: Api
          Properties:
            Path: /
            Method: POST
