AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CHANGEME
Resources:
  CHANGEME:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/events/CHANGME.handler
      Runtime: nodejs8.10
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref CHANGEMEAPI
        PostResource:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId: !Ref CHANGEMEAPI

  CHANGEMEAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: 2.0
        info:
          title: CHANGEME
          description: CHANGEME
          version: 1.0.0
        paths:
          /:
            get:
              summary: CHANGEME
              description: CHANGEME
              produces:
                - application/json
              parameters:
              responses:
                '200':
                  description: Successful operation
                '400':
                  description: Invalid input provided
                  schema:
                    $ref: "#/definitions/ErrorResponse"
                '500':
                  description: Unhandled error
                  schema:
                    $ref: "#/definitions/ErrorResponse"

              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 200

                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CHANGEME.Arn}/invocations"

                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy

            post:
              summary: CHANGEME
              description: CHANGEME
              consumes:
                - application/json
              produces:
                - application/json
              parameters:
                - name: body
                  in: body
                  description: The data for the method
                  required: false
                  schema:
                    $ref: "#/definitions/DataInput"

              responses:
                '200':
                  description: Successful operation
                '400':
                  description: Invalid input provided
                  schema:
                    $ref: "#/definitions/ErrorResponse"
                '500':
                  description: Unhandled error
                  schema:
                    $ref: "#/definitions/ErrorResponse"

              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 200

                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CHANGEME.Arn}/invocations"

                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy

        definitions:
          DataInput:
            properties:

          ErrorResponse:
            properties:
              error:
                type: string
                description: Error message
