AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World
Resources:
  HelloWorldTS:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/events/helloWorld.handler
      Runtime: nodejs8.10
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: HelloWorldTSApi
        PostResource:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId: HelloWorldTSApi

  HelloWorldTSApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        paths:
          /:
            get:
              summary: Get a hello message
              description: Returns a JSON string with a nice message
              produces:
                - application/json
              parameters:
                - name: word
                  in: query
                  description: A word to use in the message
                  required: false
                  type: string
              responses:
                "200":
                  description: Successful operation
                  schema:
                    type: string
                "400":
                  description: Invalid word provided
                  schema:
                    $ref: "#/definitions/ErrorResponse"
                "500":
                  description: Unhandled error
                  schema:
                    $ref: "#/definitions/ErrorResponse"

            post:
              summary: Produce a hello message
              description: Returns a JSON string with a nice message
              consumes:
                - application/json
              produces:
                - application/json
              parameters:
                - name: body
                  in: body
                  description: The data for the method
                  required: false
                  schema:
                    $ref: "#/definitions/DataInput"

              responses:
                "200":
                  description: Successful operation
                  schema:
                    type: string
                "400":
                  description: Invalid word provided
                  schema:
                    $ref: "#/definitions/ErrorResponse"
                "500":
                  description: Unhandled error
                  schema:
                    $ref: "#/definitions/ErrorResponse"

        definitions:
          DataInput:
            properties:
              word:
                type: string
                description: Word to be used in the message

          ErrorResponse:
            properties:
              error:
                type: string
                description: Error message
